### ISSUE TITLE
Create Support Component

### ISSUE THREAD

**Issue by nyongho11** [codestates/Wecomony-client#11]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Create Support Page
### TODO
1. [ ] 문의 제목 작성 칸 만들기
2. [ ] 문의 카테고리 고르는 칸 만들기
2. [ ] 문의 내용 작성 칸 만들기
3. [ ] 제출하기 버튼 만들기
4. [ ] 취소 버튼 만들기
4. [ ] 제출이 완료됐다는 메세지 ("고객님의 소중한 의견에 감사드립니다.") 띄우기
### Estimated time
> Pick one

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Urgency:  `Low`
