### ISSUE TITLE
Create Modal onClick My Account

### ISSUE THREAD

**Issue by nyongho11** [codestates/Wecomony-client#16]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: Create account page 
### TODO
1. [ ] Nav 바의 "우리 가계부" 를 눌렀을 때 hasAccount: 0 이면 "위코노미 생성", "위코노미 참여"  두 가지 선택창의 모달창 띄우기.
2. [ ] "위코노미 참여" 선택 시 바로 내 가계부 페이지로 라우팅하기.
3. [ ] "그룹 참여" 선택 시 "그룹 코드" 입력한 이후 해당하는 그룹의 가계부 페이지로 라우팅하기. 
### Estimated time
> Pick one

### Labels
- Estimated time: `E: 5h`
- Group : `client`
- Urgency: `High`
