### ISSUE TITLE
Create Right side bar Component (status member)

### ISSUE THREAD

**Issue by ning1315** [codestates/Wecomony-client#18]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: fix actions from client redux
- 
### TODO
1. [ ] 우측 상태바 컴포넌트 제작
2. [ ] 그룹초대 버튼
3. [ ] 어드민일시 그룹관리 버튼
4. [ ] 그룹 멤버 리스트 보여주기.
5. [ ] 각자 역할 보여주기.
6. [ ] 팀 리더는 왕관 아이콘 붙혀주기.

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
**Additional context**
