### ISSUE TITLE
Create Main Page Component

### ISSUE THREAD

**Issue by nyongho11** [codestates/Wecomony-client#7]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 
### TODO
1. [x] 서비스 소개 페이지
2. [x] 서비스 기능 소개 페이지
3. [x] 회원가입 시 가능한 기능 소개 페이지 
4. [x] 페이지 후기 컨텐츠 페이지
5. [x] 이용자 수 소개 페이지 ( + 위로가기 버튼)
### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Urgency: `High`
